<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StudentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $students = [
            // Data kelas 7A
            ['nama' => 'akhmadrendywiranata', 'kode' => '7A-01'],
            ['nama' => 'aliciawijayasie', 'kode' => '7A-02'],
            ['nama' => 'alifiandrorajendra', 'kode' => '7A-03'],
            ['nama' => 'anggundindachristianti', 'kode' => '7A-04'],
            ['nama' => 'aryaputraekanugraha', 'kode' => '7A-05'],
            ['nama' => 'azahrazaskiaputri', 'kode' => '7A-06'],
            ['nama' => 'carrissaartantizikriyyaazzarah', 'kode' => '7A-07'],
            ['nama' => 'celinelauismargareta', 'kode' => '7A-08'],
            ['nama' => 'cherylnaumihotmam', 'kode' => '7A-09'],
            ['nama' => 'evitamuninggardahayuwicaksono', 'kode' => '7A-10'],
            ['nama' => 'feliciakireinajosephine', 'kode' => '7A-11'],
            ['nama' => 'haidaralfarezelenasmuttaqin', 'kode' => '7A-12'],
            ['nama' => 'jazlinazzahra', 'kode' => '7A-13'],
            ['nama' => 'lindzeemeccawidjaya', 'kode' => '7A-14'],
            ['nama' => 'matthewadrielhutagaol', 'kode' => '7A-15'],
            ['nama' => 'meyshaputriayuwulansari', 'kode' => '7A-16'],
            ['nama' => 'mochnovalarifin', 'kode' => '7A-17'],
            ['nama' => 'muhammadnizamjuniarakbar', 'kode' => '7A-18'],
            ['nama' => 'naufalazkairwansyah', 'kode' => '7A-19'],
            ['nama' => 'ngestitaniddowijaya', 'kode' => '7A-20'],
            ['nama' => 'princessjavelinbiancadetta', 'kode' => '7A-21'],
            ['nama' => 'rayhanfadheelsaputra', 'kode' => '7A-22'],
            ['nama' => 'revanaylasalsabila', 'kode' => '7A-23'],
            ['nama' => 'reysakamilalfarizy', 'kode' => '7A-24'],
            ['nama' => 'ricoalvaro', 'kode' => '7A-25'],
            ['nama' => 'salsafitrijezialensyasetiawan', 'kode' => '7A-26'],
            ['nama' => 'septyanaaliciaagustin', 'kode' => '7A-27'],
            ['nama' => 'vaniafebbyw', 'kode' => '7A-28'],
            ['nama' => 'yafetnickohermawan', 'kode' => '7A-29'],
            ['nama' => 'yaqzhanrajeshtursinayudi', 'kode' => '7A-30'],
            ['nama' => 'yasminekhaliesahadeeva', 'kode' => '7A-31'],
            ['nama' => 'yogapratamasantuso', 'kode' => '7A-32'],

            // Data kelas 7B
            ['nama' => 'achmadrifkialamsya', 'kode' => '7B-01'],
            ['nama' => 'aleeshaavariellairianto', 'kode' => '7B-02'],
            ['nama' => 'amandafebrianti', 'kode' => '7B-03'],
            ['nama' => 'arnindyagadiszabrinamahewsari', 'kode' => '7B-04'],
            ['nama' => 'atharridhodwiatmaja', 'kode' => '7B-05'],
            ['nama' => 'athifgalenoputravolianto', 'kode' => '7B-06'],
            ['nama' => 'auliarizkyanantasari', 'kode' => '7B-07'],
            ['nama' => 'auroraeiliyahparveen', 'kode' => '7B-08'],
            ['nama' => 'cahayalintangmahasmaralaksono', 'kode' => '7B-09'],
            ['nama' => 'chandramaygantriaji', 'kode' => '7B-10'],
            ['nama' => 'deandrareysa', 'kode' => '7B-11'],
            ['nama' => 'desitrihana', 'kode' => '7B-12'],
            ['nama' => 'fathinadelio', 'kode' => '7B-13'],
            ['nama' => 'friskazhafira', 'kode' => '7B-14'],
            ['nama' => 'kuruniadyasheikkaramadhani', 'kode' => '7B-15'],
            ['nama' => 'muhammadadzinjavasputrawibowo', 'kode' => '7B-16'],
            ['nama' => 'muhammadaliffirmansyah', 'kode' => '7B-17'],
            ['nama' => 'muhammadsarifhabibullah', 'kode' => '7B-18'],
            ['nama' => 'muhammadzakkyabidin', 'kode' => '7B-19'],
            ['nama' => 'neyralatishaevelyn', 'kode' => '7B-20'],
            ['nama' => 'novalarianto', 'kode' => '7B-21'],
            ['nama' => 'princesskaylasalsabillarazak', 'kode' => '7B-22'],
            ['nama' => 'queennadineaylaazzura', 'kode' => '7B-23'],
            ['nama' => 'rachmadheachalistaagusti', 'kode' => '7B-24'],
            ['nama' => 'rahayunovitasari', 'kode' => '7B-25'],
            ['nama' => 'sabrinazanubaturohman', 'kode' => '7B-26'],
            ['nama' => 'safiradwiapriliaputri', 'kode' => '7B-27'],
            ['nama' => 'shofyanidfirulaziz', 'kode' => '7B-28'],
            ['nama' => 'vierravillasanty', 'kode' => '7B-29'],
            ['nama' => 'widyasekarnurharyanti', 'kode' => '7B-30'],

            // Data kelas 8A
            ['nama' => 'abeliaputrilistiyasari', 'kode' => '8A-01'],
            ['nama' => 'albertwicaksono', 'kode' => '8A-02'],
            ['nama' => 'angeliarinindraitaliaputri', 'kode' => '8A-03'],
            ['nama' => 'anisaturroikha', 'kode' => '8A-04'],
            ['nama' => 'arlenenathaniafebart', 'kode' => '8A-05'],
            ['nama' => 'athafarelputramachmudi', 'kode' => '8A-06'],
            ['nama' => 'azillapurioctaviona', 'kode' => '8A-07'],
            ['nama' => 'barqibaharatalail', 'kode' => '8A-08'],
            ['nama' => 'brianaufaashar', 'kode' => '8A-09'],
            ['nama' => 'caesarirsyadhakiim', 'kode' => '8A-10'],
            ['nama' => 'devanvalentinoardilian', 'kode' => '8A-11'],
            ['nama' => 'fakhrizalizzatwibawa', 'kode' => '8A-12'],
            ['nama' => 'fanesyaputrialeyarahma', 'kode' => '8A-13'],
            ['nama' => 'fitrahardiansyah', 'kode' => '8A-14'],
            ['nama' => 'ghaniyyarizkiana', 'kode' => '8A-15'],
            ['nama' => 'irfanbakhriramadan', 'kode' => '8A-16'],
            ['nama' => 'isimfaail', 'kode' => '8A-17'],
            ['nama' => 'jessicaputriimanuel', 'kode' => '8A-18'],
            ['nama' => 'kevinputrapratama', 'kode' => '8A-19'],
            ['nama' => 'landiridhofadilah', 'kode' => '8A-20'],
            ['nama' => 'mhaidarulriadiputra', 'kode' => '8A-21'],
            ['nama' => 'mochaziztaqiyyudin', 'kode' => '8A-22'],
            ['nama' => 'mohfaisal', 'kode' => '8A-23'],
            ['nama' => 'mohammadrevanggaberlianoheru', 'kode' => '8A-24'],
            ['nama' => 'muhamadfamaputrapratama', 'kode' => '8A-25'],
            ['nama' => 'muhammadnandasyahputra', 'kode' => '8A-26'],
            ['nama' => 'najelaaathayanailirrahma', 'kode' => '8A-27'],
            ['nama' => 'ollanmegaliyantiwildanaya', 'kode' => '8A-28'],
            ['nama' => 'prayogarakaaryapradipta', 'kode' => '8A-29'],
            ['nama' => 'rafaelefranratmoko', 'kode' => '8A-30'],
            ['nama' => 'robyfarrozalali', 'kode' => '8A-31'],
            ['nama' => 'shafasalsabilakurniawanputri', 'kode' => '8A-32'],
            ['nama' => 'tabitaeklesiastefani', 'kode' => '8A-33'],
            ['nama' => 'tirtabening', 'kode' => '8A-34'],
            ['nama' => 'wishnuramadhan', 'kode' => '8A-35'],
            ['nama' => 'yonaviscamagdalenaputri', 'kode' => '8A-36'],
            ['nama' => 'zahraazkiyaramadhani', 'kode' => '8A-37'],
            // Data kelas 8B
            ['nama' => 'abiyneoravariaco', 'kode' => '8B-01'],
            ['nama' => 'adhwahanumsyafiqoh', 'kode' => '8B-02'],
            ['nama' => 'afriansyahdwiprasetyo', 'kode' => '8B-03'],
            ['nama' => 'alaricvalianttiebout', 'kode' => '8B-04'],
            ['nama' => 'alimustofasyahroudhi', 'kode' => '8B-05'],
            ['nama' => 'alsalyciaauroranefannie', 'kode' => '8B-06'],
            ['nama' => 'anaroudhomirriyadiljannah', 'kode' => '8B-07'],
            ['nama' => 'ayeshanayellazaindanuputri', 'kode' => '8B-08'],
            ['nama' => 'azzaraarlettanissa', 'kode' => '8B-09'],
            ['nama' => 'chestazidansabilillah', 'kode' => '8B-10'],
            ['nama' => 'dwibuanatunggadewiainiya', 'kode' => '8B-11'],
            ['nama' => 'egyputramahardika', 'kode' => '8B-12'],
            ['nama' => 'febiogavinazarya', 'kode' => '8B-13'],
            ['nama' => 'ibrafazaramadhan', 'kode' => '8B-14'],
            ['nama' => 'jafarsofvanza', 'kode' => '8B-15'],
            ['nama' => 'lucreziasuaidatulbeatrice', 'kode' => '8B-16'],
            ['nama' => 'marshadwianggraeni', 'kode' => '8B-17'],
            ['nama' => 'mochammadriskiraditiyah', 'kode' => '8B-18'],
            ['nama' => 'muchamadilhamabdillah', 'kode' => '8B-19'],
            ['nama' => 'muhammadarshyatalathaputrasasongko', 'kode' => '8B-20'],
            ['nama' => 'muhammadazkyfahrurreza', 'kode' => '8B-21'],
            ['nama' => 'muhammaddanialrafarabbani', 'kode' => '8B-22'],
            ['nama' => 'muhammaddimasaryokusumo', 'kode' => '8B-23'],
            ['nama' => 'muhammadfahmiroychanabdillah', 'kode' => '8B-24'],
            ['nama' => 'muhammadzakifahrezafirdaus', 'kode' => '8B-25'],
            ['nama' => 'narayanasatriyadarusalam', 'kode' => '8B-26'],
            ['nama' => 'naufaltrisanosetiawan', 'kode' => '8B-27'],
            ['nama' => 'nyokoshintahardiyanti', 'kode' => '8B-28'],
            ['nama' => 'rahesyaputrasutaman', 'kode' => '8B-29'],
            ['nama' => 'rizahsalsabilah', 'kode' => '8B-30'],
            ['nama' => 'rolandabungaayu', 'kode' => '8B-31'],
            ['nama' => 'salsaelisdwinovita', 'kode' => '8B-32'],
            ['nama' => 'saveromaheswaraatmaja', 'kode' => '8B-33'],
            ['nama' => 'sutanharyoanggoro', 'kode' => '8B-34'],
            ['nama' => 'syaviranindyaaini', 'kode' => '8B-35'],
            ['nama' => 'thoriqurrafidar', 'kode' => '8B-36'],
            ['nama' => 'vinoaldiladymitri', 'kode' => '8B-37'],

            // Data kelas 9A
            ['nama' => 'adelairaclarissamuriestasharin', 'kode' => '9A-01'],
            ['nama' => 'afandiaryaprastya', 'kode' => '9A-02'],
            ['nama' => 'aureliarachelnathania', 'kode' => '9A-03'],
            ['nama' => 'azaliasalsabiladiwharthy', 'kode' => '9A-04'],
            ['nama' => 'callistabellaharyadi', 'kode' => '9A-05'],
            ['nama' => 'darrylcapriantcaesario', 'kode' => '9A-06'],
            ['nama' => 'dittanazwayuliaputri', 'kode' => '9A-07'],
            ['nama' => 'febrianalbykusumanadezhda', 'kode' => '9A-08'],
            ['nama' => 'gandaratirtaakhmadmulyanegara', 'kode' => '9A-09'],
            ['nama' => 'henochchristianruntutputra', 'kode' => '9A-10'],
            ['nama' => 'jivoalbertohagaisimamora', 'kode' => '9A-11'],
            ['nama' => 'lauranovalia', 'kode' => '9A-12'],
            ['nama' => 'marcelinomegakurniawan', 'kode' => '9A-13'],
            ['nama' => 'marcelleliadinata', 'kode' => '9A-14'],
            ['nama' => 'minhatulmaulanovdianti', 'kode' => '9A-15'],
            ['nama' => 'muhammadalifachrizikurniawan', 'kode' => '9A-16'],
            ['nama' => 'muhammadmisbakhusbaihaqi', 'kode' => '9A-17'],
            ['nama' => 'naifhamadibrahim', 'kode' => '9A-18'],
            ['nama' => 'narendrabayuaji', 'kode' => '9A-19'],
            ['nama' => 'quinsaaprilitaamaranggana', 'kode' => '9A-20'],
            ['nama' => 'rasyaazrielramadhan', 'kode' => '9A-21'],
            ['nama' => 'ristawulandarifirdaus', 'kode' => '9A-22'],
            ['nama' => 'theresashizuabhita', 'kode' => '9A-23'],
            ['nama' => 'ukasahabdurrochman', 'kode' => '9A-24'],

             // Data kelas 9B
             ['nama' => 'aisyaaureliaprincessa', 'kode' => '9B-01'],
             ['nama' => 'aisyahnurjannah', 'kode' => '9B-02'],
             ['nama' => 'amandanailasavira', 'kode' => '9B-03'],
             ['nama' => 'amelliasilvianafitri', 'kode' => '9B-04'],
             ['nama' => 'arokdigdayaparasdya', 'kode' => '9B-05'],
             ['nama' => 'cathrynemaharanigratillia', 'kode' => '9B-06'],
             ['nama' => 'celloadillapasha', 'kode' => '9B-07'],
             ['nama' => 'dikadwiirwansyah', 'kode' => '9B-08'],
             ['nama' => 'keylafriskalarasati', 'kode' => '9B-09'],
             ['nama' => 'mosesimanuellyostami', 'kode' => '9B-10'],
             ['nama' => 'muhamadwibiherdiansyah', 'kode' => '9B-11'],
             ['nama' => 'muhammadjiwanggaputrapriyandika', 'kode' => '9B-12'],
             ['nama' => 'nastitiswimaarif', 'kode' => '9B-13'],
             ['nama' => 'oktavanoghanifalkahfi', 'kode' => '9B-14'],
             ['nama' => 'pargatahalutaraka', 'kode' => '9B-15'],
             ['nama' => 'quansanitasharonphilia', 'kode' => '9B-16'],
             ['nama' => 'ranggadwiprasetya', 'kode' => '9B-17'],
             ['nama' => 'renatabebyhafizah', 'kode' => '9B-18'],
             ['nama' => 'rizkynovianprasetyo', 'kode' => '9B-19'],
             ['nama' => 'salsabilameriyanaputri', 'kode' => '9B-20'],
             ['nama' => 'satrioputrasejati', 'kode' => '9B-21'],
             ['nama' => 'vanianurazizahaminudin', 'kode' => '9B-22'],
             ['nama' => 'wiranatabielvazhafifpratama', 'kode' => '9B-23'],
             ['nama' => 'yolandaanastasyaputri', 'kode' => '9B-24'],
        ];

        DB::table('murids')->insert($students);
    }
}
